from selenium.webdriver.common.by import By

class DegiLocators:
    ellipses_button = (By.CSS_SELECTOR, ".nebula-table__row td[data-label='Actions']")
    unassign_button_on_popup = (By.CSS_SELECTOR, ".nebula-modal__inner button#unassign-assignment")
    unassign_button = (By.CSS_SELECTOR, ".assignment-list__action:nth-child(4)")
    number_of_assignments = (By.CSS_SELECTOR, "td[data-label='Actions'] .nebula-dropdown button.nebula-button--ghost")
    assignment_manager_button = (By.CSS_SELECTOR, ".nebula-global-nav .nebula-global-nav-item[href*='/learn/assignments']")
    global_navigation_hamburger_menu = (By.CSS_SELECTOR, ".nebula-product-bar__global-nav-button")
    assignment_name_on_table = (By.CSS_SELECTOR, ".assignment-link-list__title-container a")
    assignment_manager_title = (By.CSS_SELECTOR, ".classrooms-layout__title")
    view_all_assignments_button = (By.CSS_SELECTOR, ".assign-page__button-container a span")
    successfully_assign_to = (By.CSS_SELECTOR, ".assign-step--four p")
    confirmation_title = (By.CSS_SELECTOR, ".assign-step--four h2")
    confirmation_final_steps = (By.CSS_SELECTOR, ".assign-page__steps-container .assign-step-tab .assign-step-tab__label--current")
    user_type_teacher_card = (By.CSS_SELECTOR, "a img[alt='educator avatar']")
    sign_up_page_label = (By.CSS_SELECTOR, ".de-form__section .comet-form__label--bold")
    signin_username_input = (By.CSS_SELECTOR, ".de-form__section input[id='username']")
    username_continue_button = (By.CSS_SELECTOR, ".comet-button")
    signin_password_input = (By.CSS_SELECTOR, ".de-form__section [id='password']")
    singin_submit_button = (By.CSS_SELECTOR, 'button[type="submit"]')
    sing_up_page_links = (By.CSS_SELECTOR, ".de-login-2021__signin-link")
    stay_signin_popup_no = (By.CSS_SELECTOR, '.nebula-button--ghost span.nebula-button__text')
    personalized_title_homepage = (By.CSS_SELECTOR, '.personalization-module__header .personalization-module__title-wrapper')
    discovery_logo_on_header = (By.CSS_SELECTOR, '[alt="Discovery Education Logo"]')
    open_profile_panel = (By.CSS_SELECTOR, 'button[aria-label="Open Profile Panel"] img')
    click_profile_panel_option = lambda option: (By.CSS_SELECTOR, "ul a[data-click-name='{}']".format(option))
    sign_out_completely = (By.CSS_SELECTOR, 'button[type="submit"]')
    back_to_home = (By.CSS_SELECTOR, '.logout__form .nebula-button--ghost')
    search_input_bar = (By.CSS_SELECTOR, '.nebula-product-bar__combobox .nebula-product-bar__search-input')
    search_page_filters = (By.CSS_SELECTOR, '.search-page__filters')
    search_results_header_line = (By.CSS_SELECTOR, '.nebula-page-container .search-summary')
    PDF_activity_card_ellipses = (By.CSS_SELECTOR, "ul .nebula-card--asset .nebula-card__action-menu button")
    PDF_activity_card_ellipses_assign_button = (By.CSS_SELECTOR, "ul li a[data-click-name='Assign']")
    create_assignment_heading = (By.CSS_SELECTOR, ".nebula-action-bar__title-grid")
    assign_to_your_student_button = (By.CSS_SELECTOR, ".dual-assign-option button[data-click-type='Assign to DE classroom']")
    choose_how_to_assign_text = (By.CSS_SELECTOR, ".dual-assign-step__heading")
    classroom_checkbox_on_assignTo = (By.CSS_SELECTOR, ".assign-step__group ul label")
    classroom_select_student_buttons = (By.CSS_SELECTOR, ".assign-step__select-students")
    assign_section_next_button = (By.CSS_SELECTOR, ".assign-page__button-container .nebula-button--fill")
    Schedule_title_on_date_page = (By.CSS_SELECTOR, ".assign-step--three")
    start_date_calender = (By.CSS_SELECTOR, ".dp__input_wrap #assign-start-date")
    select_date_button = (By.CSS_SELECTOR, ".nebula-button--fill")
    due_date_calender = (By.CSS_SELECTOR, ".dp__input_wrap #assign-due-date")
    schedule_assign_button = (By.CSS_SELECTOR, ".assign-page__assign-container .nebula-button--fill")
    select_date = (By.CSS_SELECTOR, ".dp__today")

